apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:uB71Iqdqv6kBi3ynSln9LsDxOKOcoVBR7GEJGrdKSavUUosFPMefLXsVnPgbIoAnSaRjoH0=,iv:a8S1wmeFgBM/MVTr7npcWbg4fWayGxI9XwumF/Sveo4=,tag:OmgLYclqs1oSyOzbbaQTXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdxSHgxbGJN
        VmpuZi85dXBzd3haMTdiUUlLRkhQSTVjbXhRbWtrYmFRZVl4ZWhiYjV3MWFHNG05
        YXFNWVNSWllTZ29OMjhxcDkwVFFPcElhRVZuYUVsMkJCM0w5QmJYWXlHNmdHVGJx
        ZmM4eDhEeExKVTNIdG4vL2hpNkZodmcyd0JRVWNxQ3B3OXFkMUw2ZzZKMFAxQ0lt
        NURFZGRIWFpsN2hnMlE5MTdkYlgrMGp1VEkwWjRGd2l1Q0NwZ084UzE1MkZZYmlr
        WS8ySDR0NXVuRXhlSzIvRGZnOTRtQW1OR1o3VzdVTnpjd3dsbndWTXdnbHdFV2Jy
        dmdDdStDaXRXeXlkVjU3akFtSWxwY1VEUEpuejVPSWNldHYrREE5TDBRY3V3bk1B
        a0paWi8rbVY0TVMxbzFKVjFuK2xZdDRxVGg2TlFiZG1mTlU2djBuUlRqaXJ5c0My
        UWhhYXpudDE5blI0ZVZRZGErUXJFb1pTZ1pxWkNFTVg5QWwwcWMwYnFib3RHcmNs
        M0xma2hPMHU4d0E5OTRwQkZFV2tMWFNJbjNRU0lubUZEWVE3YlI4UVpUamVvQVZl
        dWIvaXpjQWtndUJHRHpRUVRRYkZtUG8zOTlKMW1ZVWJRVW01RHZPWWlvMnc4bzJD
        MXhMU1RIVWhmL1pYUy8zNGNhVzlYRnR5WFBNZUtGbzgraTNrd2xONzZaWEVENVhr
        VGRTaE8xbFBPZGM0OThrWHpwRG5TcSs4dk1GWlpxYUlPUWFkOUJUZkt0NkpRTTht
        bi9PdjlPTFl5WGIwM1hhZ0o2eFh3VVlaUzBTMENSYXREZUc0QitQaExrRnc4ZWs3
        VHVXV1hPdGJJblJMY2w3VDZDY3FGcEYvU1ZNQ1NQU2xVTFpiVjRJUWZrajZBL2ZR
        OWhGeklBMDAxTDVMc2NFb0d5MDIwR3FEV1hoaWFZYVRtTjViL1hRN3dFM1F5a01R
        V1NFcXpuaXVKMytvc3hHNEd2dXBGS1htdVU5RFp0ZDd4dVM3YStLNFF6WUF1aTBW
        UE01VHJnaXNyYjI2eGZxZkZuR0Y0a2U1aVBtekFkTUw2clVFM3VHRitaemhHaStq
        VEwwaS95WjZRTnlHZXUrSHlQcTVmUStjb1FHYVBoT2lTcTJMb2w0V0c0OEs2b0pL
        aDQ5dUJiSDNRMWVmQ3BqeUkvNHd3UEJTTldOQzVCYjRhTjZFZzZVcTRWRE5FQkRZ
        NkZnN3ZRajYzRVFsYkhxRWhiaEJzNWZKL2d6cndRVGRpamdieEdiTTVBTllmUWlG
        eXJHVXYvck40cmZFdTNTUkY2bCtvYm85emIrZGQxZUJIMmthcUlBbW9PK3hQbGhX
        ZmJnUWdNbUpQZUhqVFVuM1pmbVkwZEhIUFdlY0dNVTFadWNoaXZsZlorckV1ZFpO
        WDEvRGlZRVdwK05PbXFWNGJSYjYraVVReEdsSGZVVHRXOWtoT1NWUTgxb0ZuRmtn
        R3UyR0Z5WHpNQ3lCUjFlQm1rK0IxenJjdGtIRkwwT1B1RkNaQ2dLZFNQRmNqdURk
        dklXeDE0RjJjYkZ0NmdLYzkyU0NFaTJBdUR0SUhVenBqNDkySnlpWkd1V2ttZW5o
        V1NPMDRKT3Z6ZFJrRXdQbEJJRW13eTNPc1JORW5KTzBsSzNVejBVc1FsVzNIbm43
        UGhhakE5bDBiQlBDTEI2cXFaU3RQK21xSHppekxXTE9SNWFoRnExN0xUaWR1RGhp
        ZTFJS1MvUkdoZU8vbWxrRWRab0dCRWZYVTZCeWhzcEkxNTRDUlArSmhHNE16akZp
        V1dSeW1jQ2dqbGJ1YUZzMHdkT244Tk0reEovb04xUXllTm9JaVpHclcwSmVpUzFZ
        c1VOUmRKR1ZUNEZXZzRaSTRwdnlHYk1rNnd6TUpXSnNDTHZOZ0tEeTNWaCsyaUho
        TzlOQVkzcUNkdzQxdVdzUEh6VDZrbUhCTTVsOVoyeERzbjVjTkpqeG1PUFZUQQp4
        ZDJJSFJrM0dQOTFHbGRZYlNoOGhBOXhnZzdTOGZyS0xwYmpUNVNCWFg0Ci0tLSBx
        WXgwc21KWUVGRUxiaEJnOGNIQU5BNXFic2dxWkNUZWYvOThDOXNKL0RvCsX2Kkrv
        Z58AGlIkIakzN1EXmDYbHDPm5+OpsnJB23ThDckKiY2YityCanG4XVxpzHLQv4i+
        YU44SDKLU11awtk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:58:30Z"
  mac: ENC[AES256_GCM,data:ia2wa/eug/VBZEiMIoyPfF2ENlMxNZwfmN3FkgBLn6559FOagjysFK7r+7RgPAKYTWjCedPfCCJDacghtq2JdLQtrulgmHQXBruO8st3Hbq2cr842bWUDiwYZ/5PxShYt2OYoisJMZrpcnjq21ezW8TFb7kdj5LjlXikLZeA4X8=,iv:hywdviFJtEzDhjjw+knESSmEzt3QKiN5w4K40xq4mwk=,tag:yJ6vYe0YbAguewayh/wBIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
