apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yxVoU92sY1XHiIJJAxd/OZ+42g9+Ph56tSW/QvtUyHrSOJXAt2o72u7j0/6oFYZwaTya6Ng=,iv:sBetVGVmZ7C8fHqMgL8NVI2KzbiWWWJC4ixHdN+Xhho=,tag:XMKLvC61yJ9XiN58bwMK+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IENWMG40Q244
        UFRFekE5bGE2a3Z2REl1MkFlSkhOa1ZnS3EvNmZyYUxXek1VcHNucUhiOTh3U0xV
        aUJ6Q1BnQU5ZRklHME9pdWxJSGorRGEycG9mNHNUQ0h3SlhJUVdhSVJsZHJNR1hK
        MTNjbmRCZHJpMWJBc2llSm5TaHVIVjJjMFM0Mko3TVBld2wvaSttam5jeUtXVXVv
        dktKZ1luSmRNNjlzNzZmK2pVM0toOVJvUGlNRUxyTXd5NWJJNmJ1eDU2L2Y0S1A4
        Y0VjQm1SMG9SYXpnZ1BxMWdRemdmc2NaSjJiUHlSN093c2ZlWWdMWVZqNjJpZjNz
        MHdJZzRFd0FLQVlSeXZVWm1nUEovTkdLbndUSEpKUW92OVRmNkFmTG1rQ1ZBZlRj
        UElzYmR4Nzd3SFdFM2R2Kzk4dEh0NlhWWDJNVlNkYmJUU29SQ0lHTU5WQW5KZlQw
        QkMvWXgyUjZlTjB0bmYzSzRXTmF6a0ZxaDB0V1ZjUnpPUnRDNEsvSnZrSVM0MTlt
        Yi9hR05rK0gxZWdsN0dzWno4cGdWVnBiSTFxMS9yeWpKN3lPeEpsM3F1bzcwZEVW
        Q3BBZVVKaTdHSHcvdEJTNk81VGhjT1VteFU5a0N0UUlGVjhlVVNCd25OYjFwSExX
        VEJudmRaZFl6Y1BXV0l6WTVRWXE2VnRpUEpoRXNBRVR1aXV1aVdsTnJ2N1RSam1o
        eEY0WmJ1Q3NRN0pMcllRcU03T0RWSVljTTcyS1FLbWlBNmZ6Z09Jdyt1WUJXL3pR
        OFJmV2hmUnJWRi9kck54SFhzanVNd0tkY2RDcXh4VTVRWjBDT3VvNElzOFVYYm1o
        Mzc1b2Nmc1JsMmNZRlEyZTRVV2YycFdsUTVhTzVKV2lKZ3UxQUdhZHllbVBhNDZR
        YTVHZlJLdWpZeGZLMlR5MUJVTDEvaDlCTlV0Mk92cjl3ZFljR1JQdlExNzM3YjQv
        RjlLVFJVRkdqeXU0Y0lVZ1d5S3B3TExWMTQ4TmR1MzMzZENibGFSWWVuWXNYSDVT
        bTBObElQN3llbGowTC93VGp3L0JMWTQ4OGcxTnZsTDdiYlIxS2JBS2tPTWpoWFdp
        c2R1TzFVZUVCOExHOFFBV2Fyd09aMVpuRCtPTHI4YnV2ZGpWQmVaTktJeEhpSFNY
        TDlvNms1WFRJRFdpL0hNS3lvR0NDbkhjdkJxK3VaMElCL1BQbVJNdFNzSVkxTTM2
        VE9YSWJMc1I1Q2NvaFpBM1RaRHk2U2VGZTcxeDUwbmxTbXNGUFVCNWIwaFI4OERk
        UElUYUVSdFFRd1gydjRxU0x2WVJMUHlTa3N0WWtoNEhJaHgxZWtkQng1N2lwbjBT
        bTZSRUh2cmE5b2p2UzcvN2xWMjdJOGI3dHlLVjhNWGJlY3pkTW4vRW5jMFdPT2lU
        NGRlb3pYNUVBS0R3UnVBaCtaSXAwZmJMeFBpSGJjL3gzRXFaeWlwLzNOTEY3bS9Q
        cTlQUTJiaTVOU3l5a0FPWTcwajNKOXVIQXB1eEZmZlNpaEJJSm1Vbmo0Y29RWmho
        RGxuYlZ0OFp0V1FneFdDeXlHWEFSMXBQblMyMm5SdmZ0SmlWYWNTQlppNXpBME82
        MXFOL3V1TzNVNVM5WlcwZXhMWGxMaUx4ME91RTZRcUZIUmRHdVY5QmI3RWxiZkh3
        c0tkM1FMZ0R1NSs2R2hjODhDcEVUNEdDMFIrZXNFYkxRNUxGdXlOT25yVU81UUI0
        VnJGZ1RFbmhINndEckVJL3dqU1d3Sm1mQ3F2QTBIeWdkcEhKZy9aZGU4Z1FPVC9x
        RVhCa0E2ZVRNbHhLYlN0UEl0N3pxeUhtUFdCKzYxZXo1aUxONms2a2lVKzQwN1px
        YjBrOUtNM0dqcktWOEpCZ3RQZ0JCQU5QNUNkMzE1WEZrNjJ5VWtGZmphTzFPYXBB
        VlNoeGpEcFlscWppYjdhZmZhUG82cXgwenFCNU9GVEdEVWl2UEQvRkdrVWNEQQpI
        OFhhZXFNQWFsaGhUeG96bUFjK1F1TnJRMXk4ZDY4SSt1cHlMWTl5VWtVCi0tLSA5
        dEZHakhabVhQR2p4dXptMlMvUE4rczkxNllRSnJiWEV4YjNoY3l3S2M4CvCHk0LR
        ZhFZxbDJIWMBs7eMj7u6hhpKXywrMtrv+6Zxk76CGqQJ++A3crBC4Ux6dNYCQsd6
        fw91u0K8d9R8pQA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:14:12Z"
  mac: ENC[AES256_GCM,data:by8d8wOQQWXXC55E6DkJEcth46phq5pYmyhKIRlBr0488DAzseMGUNkdw1/et0IrHTDEYHnOiARBo6B35kSsx81dXDbKDj74nl5Clms/QmaL+8cjr7vWoW5/iHJGruLT+zYHpCA1BQCwzbjnOGDZzEP7ppNKJ8fLjcOowKIh0Vs=,iv:7U6+itsvvCV2PydFX7okahFhkk4IGraLEowH4JsQu30=,tag:7AywCRImDPxu2txMCSMWPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
