apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jImDfUOryJj8IOFjHmM=,iv:ZaqOaVUMgetJjQKSmPRTxgaRz1xvRm5dRmu2pY/RDro=,tag:dUHeQvHa1guRB6qiq7LubQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGg2eWd1Znh1
        L3ppSEpmWUcxdi91ZVZONUEyKzR4OVE2c1VBSGdmckFPY3FpUk44WE1BK0ZKWDlx
        a0EzSmZhU0xBblI4WDA4QkZZRmlzNTdyVDFkK3lBekhjK25nZm10OFB2Rkk5Z3Bm
        cUFQVG5qaDNuMGI3QUZ4UG5hb2YxVU4wUjFPbHJ5d1gvU04rK3pJM1ZxZThXSjZV
        bnBvaHJyMnNCYTgxanlIYlF1TWhubnBCUngwcHZiRzBOQWZod3pSeW05bTArcGd5
        YytHRGpmaVljUTRUNHBzbjY1aWtNaGR3Q3JUR3BJSU9Cd3RkdHpsZ1BWNjZ5aUUr
        T096NzV6T0hPWUZobnB1YWdXWVhEdW8rZzI2bTlRYnlVZVJUMy9Bemc1OG83bEZV
        NzUvblM2NlZWdGdVazhEYnhsZlRJVmx5bjU0eUtHWnNiYXpIMXpOajBhTzJBWUVk
        bHI3a0Rtc0dBaTM3Z2pzZitvVUxkdmlrZjcyVW5wVTNlN1ZsOXpPcmE0MFMrM3Bq
        Y1VNMWpMdGtrV1l0bC9PU1VPNnV5YTBtdEdhNlpvOTdlZytRdUlRN1ZVeURncFNz
        c2Y4VGNuSGVlTktNaklhemp6aXJLdzlVVmJSOEFPbFlteS9WRi8yQXd3VzFTZThn
        M0VqWS9hYm5xRDE1aXI1QWZnbVFFb2oraVloWndtVHdXeU90RlN5NWRjSFZWVVk5
        M09ZbWNsY29EOWhVbGFhVThycE1MZXorS3FDUUJsQlB2R0lUWE4wU09XdzhaV3JB
        SExibXVoVzVra1UzZWViNXUwWVJvNGM2SFdGcitRSkU1Q1I1a1ZZektMdGFEazV1
        a2JZOEZQc3hRQldZR0o1RXo0YnNnc0ZjTnBtOVRTaDNSc3poeUdzQTljV1V2Q0t1
        dHZGWDNRVEdobllpR1ZqWmdkbm1KUW5wZWxtMW1aZERiaFpRK21WV053enBPejZz
        YWRuOGwvY1VlbG5QUnpQUjAzbHJHd0o4NDg4R2hndW9kVjErOEtxVkxUTXk2SlVK
        UTU3c0Y1NnRWeCtlTUFacVBUekxiU1czSExidlFuTjRHeUNIQVdZcWljUEVISlRm
        Tnd2bGhXY2p4TEtKbGpDRG50RlJlTkp1cUhNdm5Sd3pNeHgrQUI0V01tN0dPdFVQ
        MUthdnhtV3ZibVQvQVpOL1lyUUhGWHlIMWFzMllXR2J0ZnhFOTRYNHFqeWw2SzFB
        YVFrQWJWa1I0Z0FQbURTUDlqV1hzV0pIcXM2cS9iV0NCTXF6S1RudWtpY1FVcnJD
        T2c3R1A1OXRITEZYMWhYQ2Qxb0ErSHpzVk9yRy9yYkY1bzVVWXZBRjlHdXYwVkJL
        OVJGYkRlM0RaUC92a2VDSVVCcnZMVFhEUkdUdXhPVGUwQ2w0cmdyQjQwZkY1T1hh
        QVZGOGZRNUxIZW1yNTcxY0h5M2RDSThSRm1odWJSSzhHeFlkSm9tdmtoVUF4S1JS
        MlJNNkxzSlZxSUZYMlljWUt2aE11WWE4ZG94NDVvbGpmVllJL3JpYStSbTgyNVNa
        b0xKeHQ1bWcwdHgxUUZVUGV6QkhYNTlyZUd2WHZ3VGRoc09KOXBwdm5ybC9mVmFG
        REswZGxDODAyWU8vVnRxL1JoTXJDSUYyL1lyRlJVUWRKZG0rWkxuVTFMNEYxYkQy
        Y0tGczdnU3dlVnFTUHFSdlNET3lITjVoSHpJNGZVK2F6N2tHdmRadkFoeEpFWUJQ
        RU9KM25PbC8vaEJQRGg0c1FoajVid1NJbHVQRElqY2FFSE9YaXcrWktCbjJSWHNo
        QjVGQnh5cmN1K3RKWWVOM3JuRHJ1dFhLNVBPenZ6VkM5QWFFa2pHQTUxUXpKYXNZ
        RmhsZGdvQ21JOXh1THhmU05aU3VmbXVQZzE5WmoyV2x0OGJsTzQ1QUUxU2NrNStE
        YzFoRFBxKzNkeGRtQk9hZE10WDl5ak1mS0x1eFM1UThObUlIYklVNTh6MzdRUQo5
        QUVSQ0xWYmVwRk1aRzg2ZVl4c0Q2dkRsOVVCa0U4VDNnZ0dDNnVEU1hVCi0tLSA0
        WTJxQVRrTEhjVzZINTI4QXZXQnRtU2dkeVZ3SmNDbkVRUUlBdndHUndZCinWRw3n
        wwAcY9uL04J7iveJNVqc7unAcfjmhCnEPD0cEBsCt394YuT2PlTE0YsIeSyy4Vym
        Ney1wO5v52e4yX8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:19:53Z"
  mac: ENC[AES256_GCM,data:D91u03cjZZ5lkaEgcMg6sYwtCLNYl0rMyzeI22+6K7cPNyVIY6r5LyqmwMhGRRXcIBSg60e8IuOoWV9zq6YgVcV4RBoxMFj+yUz9dlyi43Vz4BzsEltbFfvDSyRchv79VPwdA0oVuLJJGHEWbpvHSfh3dGGBneazl63vKHaKtP8=,iv:x6NViXmTyRu5Q9XSDwyMNMxWjm6f38zUEcDgsRx/SoI=,tag:O2twiOgVa0PUhAKbWYlPSw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
