apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Ll4i/d6etwMmvbgHklo=,iv:/f7/iw/27qa/r9wBoK+RAYIj6jYFNy2unpA8DfPcpzI=,tag:YDDh4H+T5mH8KmKIzIv7dw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGhEc0JPL1My
        ZGd5ZEVQSkJCbllWQUVUV3hYYVlrOWZDMHhBWnJ5b1Q2bXV0STV1UXdXU1JZWHhz
        emN3VGp2MnQ3eVc5ZGNUa1RoQlZvbG9zV2RrcTRrTHh6QVhkMHJCQXprUzhoKzV2
        aGk2bTR2dnQrMkpkcVI0YXV1MFp6cW5oWS80Y20xSm5JNEZxdm9lSXh0eENROHNo
        aUxxL3BKZFFpM3BoY1pmUmpTblVhWlZtTisvSjh1TXBPejRjY0g5MDBmdHFVVWVD
        ZFpMSjFuYks4SEdjdmZYR1F5N0dac0MxZHU5MmxEVTFxOWtYWDczOVFidDFNMENp
        Nko1TjJFdGUwanAwSXFrVlhIQndldmF1dE9wNUQ4eXBBQ1lkWXduS2NUd0hLNTFL
        c1NIRC9XVjAyTWlTVTdVZ2tzRk13Z3BqMnB4Wk1ubUdZeWI2THl6UFMrVWtNMzQ2
        SDRpY0ZFNWdtWlV4Y0N2MnR3b0hJV01sencyamJISkUraHU3STdianZuenhpaUhr
        L24xdzdYWVpLWnhwZnNMSy9LUW1TSytBRmhIUWhFK1l1Um1wd0J2S0p2VDNmRzFx
        aUNHcWhwMURzeVJ1MnRQZ293TmowcHB3ZlgrSWZaZTZHT3RvZ1BoU3MzRkxXVnFz
        NVFCOGRuenkxMVNpellROHkwOVl0VE9tRjdrWFFEV29PNm5EZHp1TExGcU0rdGh6
        QnRUSTNISEJhTERPNlR6Q3FIMWdsU21uT2IxMEYydEZVam1FeHcxYTNtOG5yc1Zs
        d2F2cVRDQWJ3TjNSRXRXaGZQOVZOYXNlTE56VmFpbHAxN1p4SGFMdENNS25maHFo
        bTRHZ2gyRFFockdzc0o2UXpIeE1XQzdNQWg2UkRoUUMzUmJySnJtNkFvNGtwMlFt
        ZU4wbHdQREhRYVpqcDU5am1EMFNwYWdrMlhBYWk0V1FRR0dSdS8rRGxvRisyUmxK
        QjJpWHFSRzhUVFpmUDZLdmxiSnV3QmVRN1RLZFpiSnZQNjdYRkxnL0FJbEVtMmc4
        YlgzZ0haSEJ1dnR5d0JzRzJGWjZGbnRoUnVidU44a1J3S05ERDZZaEFqYWtCZmtm
        R0J5d3BXdGtRYU5PdnF3UW93MWg1QjhFTVBYbUREaVc1VXBlSEk0N29NRzlMVDNz
        MFhNM1E5ZE84WHBRRHpMcURjRDN6U0pISjlma2ZKM1V3cS91OGFySXdsSUIyQTVJ
        TkNuQVdEQVhEd1plTXIyRnZWZWVobXhqRlE2SFphc2w0cW5rcWhvczNYM2lrRWYx
        UTBQUnJwdXZPSlBWeEUweFFTNW50TFg3bWs1TW1QUzlmV0N4UVFCQVdRQWlQU0hi
        Z2lFbUtrdE50TUlDWk93b3VySitBU2JSZmRYQkNLRTZ5Zm83YWlxR1NGUjdDaHV6
        VG5MeGdWWjBXdDZ1WjRJVTlseEc3TXdKUkJYSXU2TVdVQnhmOXZ6cUFrNm5aU3Za
        WUFKQXNxMEdlMVp4V2RhTm5pdm56Q3pTazY0R2k3RXRkVm5GcGszK3Bqb1FmVWo3
        S1IwcndDcnJqN214M2ozaXBJSFRyQm4yYmtMcjdmTzZOZVVPcUl3NHE0TFUxY2hw
        VENtcmx6N1dlWGxnWTNodEpWVnhjNlY1UVN2L2YzamVIUFJCRTFBdlErNnVpaGRa
        K3JBdzhhd2lWNWF1ckRKSXpPcjBJeWEwSWt0U0wzb0VSUHQwZmJGb29sRStSZE5o
        d280cS9JWWYzSFA1TzljSjcrU3NZVjlabkNWY0pTNDlqWmJKMUlZSVFMRDZYeldw
        SC9QdDl4K3d3cVo0dUszamlrdkVabVovNWlqL0NuVlNyVitkaVQ2eS9WQXVCbGVz
        SDgzcEpsSjJMcDVBTUhmZTl6eWd5Mi9hb0tBTlh5ek83MGgreUowQ29IM0w1T3Ew
        aVNMMStsTDdrNmlEeUFoK1BlR0VxOEhHMTBGVkZJajJ1djJoNHQ5QktjTlFSZwpj
        bDBoaEtoUGhaR3RLREh3VGpaaFBqMzBOTWpHajFZNEE4S05sbHFVTXpvCi0tLSBq
        S3hUUUdET3FzWDNNWDB5N1RhTTVzVW96OWY3bE1pSklFdW1FcjR1Q2hBCjl25oPS
        cCnR/Z2RLlMwOlPSoY/ZOlSpO4NLq7wVc03fH7iAD01EmPyfFtwc0v3JMplvxVae
        r8t5vZauoEvP2Xo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:58:30Z"
  mac: ENC[AES256_GCM,data:uGgmP3e1HbskOCAJsWg1UktESCFrBL1k7xryT19u06d+8YHRrDlHwHCcKDWdAh6gjc2ZWf3QEShsFO9fyeBkVpZjVrD7cPCj8QWrULrrznsGXJWUfxw3E861bVinsuA3tfEwJiF4GLtRCviknwbZbVpZ9WdKMUMeLMj66f8YdhI=,iv:Hz8g1ZkAwdyxRY1KJMlW56oSi1IOplG7J5Q9mpeGBlM=,tag:rMM8TjzqlaW2synGmfOmMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
