apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0vbUq3sCnX/MZb3IuA0=,iv:pqqOnwiUtfB6tKWx41OQW8QGU9u41FWl4BSs/s24VJc=,tag:J8O94Ee9ZgfgzzD8ItBCTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtFbElSYXpm
        UUYxS1dWOGJOWlQxYitnUEpDM1ZnMVlQR2tMNVRhRnNSK2xia1J4dUFCdi9NaVpN
        WDRwQzFjWDFZSE80cm1rT0F1a2xoYVppRjFaVW4yTU5VYmVZbXdOTjZyRk9BTkMz
        NThGbFdtanIvbHFsOHFSS1ZpUlh6cmVISVVlalE5Z3Y4N1FzY3N3VUk5clRVREcr
        cUh2ZW1KUU1BbjdaZlM3TE1xajV6UFlxTUZZQkxvT2VCeDJWTUZIN2U1bUZHQk9R
        RE43S2pheDFDQzF2TlBHZW5ma1RIeXhEMXlkemtRbFhDSlNhMXpZOXQxcFVTOXVG
        cUg2b1U5bm9ZSTZOMWJSSDBvYlJ5cXRlemIwREMxWjNza0JKbTNadWZIRURVRVdW
        L0svaUd6UFh0MVFBV1dEUWR2aTNMY1o3dnVKYWxSci9jVWh1ZHVvZVNkTzF1ZTA4
        NHh5NHhZZEVLV0JGdStnb1dzZ2NTOGlhZ1BWRUtuVnhhWG1CaFZ0VFc1SEVJZ2Ns
        M3ZxSUJ1Yldjc3RqZmh1Z3dZMnY3ZUVIQWF6bFU4Um84SERLRGJZYldFVHFZS21n
        NnVYQUJrZ29acnBKK2xWVkEzUU1ZaEo4dTVBMldDcEZZR0VjaXU2WlFnam1xRjFU
        QktYZHJLR3cySmY5T0JqVXlnYUdUejlSRVZSay9YUW5abnpYYnJ2aksvYjg5bkp6
        ZWdIbnNieis4VmwrbW9pVHd2ei9PY3hlLzNKM1dSUlZtZlduVk55UndQcXBMVkpG
        V0NvNExqeE1SK2haNXRYVVpXSXBheWVMQ1dyc1FzL2RyMTBKWExLL20ySTBIRllT
        bkg2K2NBZkN5YmxsMTc3c21UbkJwTU5tWW94YjVIdG1RazhkRXpHNU11UVhNemFF
        dGpQSUt1OVFGSlJuSkJXdEN2aXNCRklZclFJRmFjQkhqYkNKMnJsVXpjZEJYVnV2
        WVRXdHpkTzlBS2VvL1NSS1RGVDlEMXRvR1ZrVUVSWGFKOVhxU0hHamJFYlBhQ04x
        OTF1dkxaTUlYZmo0OFNEbVllQ3hMV3Q3R3BxMFEyK3ROZXBCY2pKZEE5Um5vRWpz
        QW13OUVTQllwdFlDekhpYnRVazlHNUVRTHNvZ0ZUcVR3SFFnK0h1R2FDNVlCaXJK
        d3JrZHgrWENnQURJbWtQL09qQXFMeEJVb3VlMHFsV3F2VVpHNkdtRTZ5emVrRWsw
        VGs3WGtnQUlKNjJoV1JQdWpjdzZrK3NqVDkwaDRqbHRsam90cXdSMUpYUzI3RDZ2
        Q0s5KzJGTXVKZkpRMjZsQTJoK3B4YWloaVdNOVRJbklINlJsb1VQRUw5LzVPWG5H
        Y1pvZm1kaVVXc2VJOFdEVGJtMVpZaVhZd2FpZWxzdklsUjdYVDczZ1hNcTF0bWRv
        YWRlc0ZhMnU3WWh0WVNjckpUV0wyUkNxb3NpODdQbElIa29IdlV1Y1RYc3dHOFVE
        b2N4R0JZdnVHVTNCWTVPdjcwbU12c2ZTMG5Qa1ZTQlZiUDFPVkIvVkExVGVZT3NT
        M1lzL3ozWmJkQmFRVUJmR0liMlAzRXVCbzRzRU1vc055Q1VEVjc0eGVEcndnTTZs
        cVYwUG5lOElHc3Bvd1kvUUpQM29VcmFhRE1hcmNMTkRTd3VuZ25mUFdtRXhmNmhT
        dHV5VjJUYXpNSm9SNk9zNE1tVTNBcTlpL2x3elB2NTNBMGpKbWlTOTlxVk02SDBL
        MWEzMXRHR0dHSjk1Rnk2dTl4cEs1aE5vb0lwYTRORllFbTRpNDZsTlliS0VRWE9i
        YU1UUFBta2dCc21rNmEvZEM3ZW8ySXAwckJGNHRBQTQzSzFzYVJrVnprRUFYTGdm
        ODVudzUxeDlOL0lneXZPRjFiN2RkK0VJN1BGZVdIbGM5K2JpNXl4S2lJbzVGWWo1
        ODltN0tvWENBUjZoL2ZqRWJvQ3ZIRFZRMU4zN3JDcmMzWXdab3dITnczVDdRdwpL
        a0IyR25LWFY0OWxVb3o1MnFFRHhOT2RUdm8xSHIvZWZZSFNablEwdjc0Ci0tLSB3
        ZGdTMFFsRk4xWTEzZTJyZDVlQ0o0ZEwrK3B6Y1VPVGUyN2JBanljMXRnChlxHe8V
        yTmLDsCdWsw74k/H3J0PsiQk/8wLmZKRLXjolfKMrtB/Z/CweFfK0BuohDSOrVgJ
        /v/+rCIN6C/O0xY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T19:42:02Z"
  mac: ENC[AES256_GCM,data:qE7AmG2P4BJsvC9cGmJcZ9fHDVLtPOzhoL3v8iUFZ6F7bdNX2UMBEIvDSFe2FBKGHrrlZ1xkqyOKlWWC8CjsMk9vFQ9fzptgSDjD8nKIZvAzhuya5zgkHajDMSy34Q8iF2QnSKcg86y8vrRgJtE/ROtOXoRQCY7WPjkdUm4+RdI=,iv:vHDDd/W9rawyy8sFjsZNFhwGxx9Px6gsK5Y8h7OG/KI=,tag:nw52oa+Ik5T2XfAt/VPQtw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
