apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:VKx6JlDFaB0uPmkw26H2NCh3nq5oJ0uFv0pSSYJ98vw=,iv:3YKq2/3rglUy8sSpPOaRQiHxq3WhZ3Oi4Rsss6w2D+k=,tag:lKqeWiu/VJ5vH5VjPyt8oQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVjc2NYMzc4
        VlFvQWF1eXNFaUpwLzFwMzI2SlFHRkZCYWE1MTNQc3RKOEJoQjlEUDVITStqR2Z6
        RGN2UWppWnUyemQxWllTSXRzTS9Fcm5raFVTVm1MakIwTGNEZzBmaVJFbHUwMXB2
        QXNmdDkwanZOUEFIK0daTlNjSHppbWphVDZWc3VSVVFobHUvTm1xY2t3a0tjZHE3
        SE5BMk1KK2xXV2dZY1J1UUh4ZHNqNTIwQUp1REl4bXRFYk5jZmNKMEQzbHJBVytB
        VmM4NkdmZHdwLzh3aHlvblhQMHA4MDF4WmlrNXNRMVUwTzRjR2hKTlgzZGoyZStI
        M2xVTVQ0V0lzYlNxUExvUDM0dSsvMi9aS1RJd09FTGd4cTF5N2FReGQ0UXFsQWhM
        ZTVXSVVUOXlGbTgyNXZia3pMSFZOVDRBWXFlNnM2L3JFSVFaWXlkY01aN3l0VmRm
        TU9lQy9QUUhJenQ0aUtNVnJHMGRZbDdFZFRqL3lHMlFpKzVPQUNsUE5PNDQyQ0tu
        eUwzaklsY2dDOTlTdXpjK2t3bUd5ek9PWGUrbHp3bE9Odk1HU3BYaWRjSmx4VEFQ
        eGlBSmt1L045UEtWSlNrT0xuTFlzemxBckZPbHlXZzF0blRNMkxTcEhyemhQdzZp
        MG5mMnZnMXJYNTkyVjlMWk52bi9aUDMybmU3c3VWSmtST1dEYzAxRExKZWZtdnc5
        aWJybHllcnhsYVZXeGcxSkoxNW42enZ0eGYwYXdWQlJzdWpRL1lXc08zUHBtNkd3
        M2NmZFJuUTNTNGZLbnE3UCt3cHErNkRvL0Mrdk5sQzNsVmpXVWJWMTl2cU1FbmNs
        ZC9UazZrRSsrdjVEY2xpWGR3Z0lUeFd4dncvRHIyYnVwZEt2b0pKaXZNK3FzRUJX
        YkxOZVY4TlprWWk0ZGpjNFNQUE8wQlc3MzBiZm9tVWM2VThqbGkvaXJ0Znp2UWZS
        NTZrUGRlR2Q4ekpnazJGNG5Qd0RxV25QM0ZCeCtVMHZBRWJlMzh4VVlEK01LSkti
        Wk1HVmZBdnZJcXptcW5RcjNSVjZFM2ExU0F6cWFCdkhWQUFydnQ2T2l1WlpDZlg0
        Vm4wMVdZQ2Ewdm4zaXhxb1VWZnpVdllYdmFqRngxT1liZldaOHZ5RjdaL05BdkY1
        eEhQUGZOQlE3QS9rZFRJNyt0dEhtZnZKK0plVEovb0VmSTJZQ0dPa3VTNWFuZ2ZC
        b2g1dFp1a2lKRU1qb0xXVEszUlhFSUlHWGhLQ1lOSHNscXNwRVdFOTRmRStURGNI
        cjIrakR6MlFRYkFxbTk2YVNiN2hMVGV6NVFnS0svcmJvang0dXdCb3F1TU4yNG5F
        K2RQeHlVRXlrTkhlMCs0UEllM3p3cGMrTVRRemN3czRGMnA4N0ZwS0k1QTNkbzFT
        Mk5iaXJMOTJxNmx4TnpZcVNIWTB6U1dPMDVHdTRPUEFUa0ZaU21ZYkFQdjlwMlVk
        ejFuL3k2Z1h1WWR6S3JRYVNDcEwySWhFYlJ0bGp6a1ZQbUZGNnB0TzBDMTZxTzFr
        OHVrNnFEMEFwbVB5aGNJRDVGRjJtLzdLcDcvTjIrcVcrUmpYNkNVdEU0NzhqZjZZ
        VVhTRU51VWg3QnRmMTZWY1ZDM3VSK0FXWUQ0SFprYnpFaHFvYjArRldUaE9PZEpI
        WVRrWExvYU5qWXMzakVvL3RhckoxOUZxVGtpYzY3UFgrcUdVZTBwSGdHOENseUtK
        YkpIZjN5Z0tVY0FSSkpobytFdnpsbE5WaTZDYUEvalhnZTgzL0wrMWV0MDBHR0xQ
        VnFmallOa3RXU1JvczRhSHFSYnpWbFdTVkcxMHhZSCswSGJndEtRRWlpUytNVVV4
        em5FanRPeE1NdThFQ3NRczVTam5hTGw5TFY5eDBGU3JGM3RHYzhIRTdaK0dMRk1E
        S3FORk1xaFowclB1Z2tSWGU4U2NvaXZrcE9FZFBWYlYwbVFzRmhDTGlsRnpEdwp4
        MVlmNFVuV1lJK2wySFVlY0tlSCtLWG84NThUYloyQ2lGT0NTTUdUbFljCi0tLSBj
        L0RHcDYzTkFUZTBMb1NqUWZ6ZWZGQklOQ1hoT05YYXpLOVFWU1ljSjFZCnbAgFET
        I9ts577OfjMplhHlzUWybLzGD5qKPiqPPAvPKWGFVLld9pwXg6ldNEjvYWc0Vx2q
        pnFQPgi9h32AAEA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:58:30Z"
  mac: ENC[AES256_GCM,data:qLSEozgPTB62ekJmBjyQkZfcpf/8HLvE0pAYLfHUbAluQfuX0ntORJD3AcuYoLP/YGleaXjl3f4yHps31hCFWJXVOAffWKc29B0OM6o4ywduLDZAwjkcWSfRfpssyp+ClFP34emyTk/thdu/NR9r1T2OScJ+6JRGVet7PXzqXMk=,iv:HQfkAH2xsDA3EnO824NseYQuKevFFEc4dZy8uVAPrzM=,tag:JeiyoovTzA2gwD0ErzGV6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
