apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:eoCuvSY9Pq9mot+HP2ufzHEMk/hJF7aAh3FBdlHGR2k=,iv:KOJm9OBMEbMW32vPdzUs4rs3W272cadbILj+wPO3XH8=,tag:NYaojmgxi1DNT7y/IMQAnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERyM1Z0K1R2
        UkRwclN0Slh2b1dVUDliaFFKQWFKNG90bXhHeDJuSnBHTXNpVUZRNXk2dDlJU0Jn
        dWdHdVE0cHRzdU5VOGczV0c2eUp3MEdrclZ4U2pVVUZZb2lBV1J1Z0tyd011N3hJ
        cDVyeHRNV21jeHNKRFFldlZnandydUZmS2RHV1RyUlNrSXkzSmkzSCtHYlQwdjMy
        V3IyNmI3dzUyYW1DYWFpb05DYjB6V2N2WjlOZU5Cejc2VFJxQ3FZRkVDU3VqR003
        dS80ZituQ2Nqb0JVSi9uMTA0YnRra3hkMTR5V3IxbUJzYy9adXhlMmxnR0FJbjhK
        ZTFWQ1NDQmNHSVdaUHcwWHR4bnJnRExUZ01UcENwZnNJdUE2SUMyTFAxRjhXblpS
        bXNjTS8vbWt1VnJ5eTU1YzlUcDhKMDA3UWowUlRFc3YzVzF4UENaUFlVSFJFTzZz
        Zk1hdDFSL2l6ZGtUUGhRZElIaUxMa2ZmWnNua3ZrdmY4SU53Z3ZaSlM4SmNzVGI1
        d3pxWDY5Qy9WdEgyVmdZYXRPS0YwTk9kM3RPUmtqNFlPZDh1dkZSWENCaWcyOFo3
        d0N0UEFZMS9tYzVIS2xYUXFIMi80VHh0SnEyanBSd0FxdDlHUWtKSU9KWnhsWkFl
        Y2pFL2htc0RGRjFoQnJqUGtRenkxOW8xaFF5YnE3NTQ2ekFwKzN3Qng1ckxKbnUv
        Zlg0SnllTUJlenVPZGFSa2gxbHN5VjBaQ1A5N0JIK00xZlBONEE1TkRjeTQ5cmhR
        NHdOVCs0ZXRUYmRkU2crcGZzSU5FN0MzNTdYNXIyYS9SWmpzVUFJMTVCQXo4dCtB
        QVFZdDduMVVpampHYzJncndlRjRCSmN0N2JmY0Z1L0NucVJsZHdhM0szVjZoN3d3
        QmthYTdUUmNHakhyaWVBdEJRWmloMzh6Y1RDUXQ0ZGIwL3ZjQ3lGcjQvYXlJQnM1
        bmhYSTA2RW80RzNZaGE3R3cxTWZmamkwaHMvT0plRmNGVi9uUjV5aSs3RThwWFlE
        MzBDS2F6d0RYWVgyM1lhK1ZwUWgwUk1wNlpBZ0h4WVhUbHAyMUExckEvYXd6UG1p
        bi9PdTRiZjVOWm9aam1lMnk2K0lDV1BHenpnTlgwNzlxV29hcE4zaCtXaGFGemsx
        djdlTkkvRnBzQjhZTjJmeDhXVHlFRzdtOTBaT1JOOXBSK1Uwejk4MlFLazlJMFV2
        VDNlQ1pQV1YxQVVJbEZNamQ5OFFsQjU1ZmhyVlJmaFM4ZUtkWWtHWFRYRkU1VnNW
        N1YwckxOdTNORHVXbWV2NzlMQmQ2Y3JvNXFIMzNkdjMwalRPcmltdHBVTmkxTTZs
        SHRseElRbVJjQ0RlNHl4VXVRV3Q4NFJQUFZlVU9ZcG52U3Y0RjlTdHlDMk5zTXIv
        ODR4UTNsTGk0UzhwS1I4eHVzeEdwMnJNQko5c2tDa1Rwd2lCdm9OSlRXSFFiNi9z
        eE02dlYycGwwVHhLVTVKNmRKWjFKaUU5alhZMzVUZEh6TTZ0eHFieFBUaWM2Ny82
        WHRWRnkwOXQxTlJrUzRvY3JVT3F5QWFNYU9MMzNNemt3S3VGSUlVRGhQZStxek1V
        OHpTeVFCQkFkUDUwcTZha095UUtBeXZuenYyaDdsVFJRa0gwS1JDZXgxOUJjbnpz
        eE1sVHJvbFIwaXplbHZsLzM3Rk5RRUJKT3owSUNpcEEwY2l6cVNzajJ6Zk4waEhk
        azBqSzhuZ1N0RnJobkZKelJjdUl5Y0wrNVJISW5EeEY5aC9PbXpqUHRzZXdORGZi
        TG81TEVPODV6MGNPYnUzc1k4b3Fwd3JPSnc0d1NHc2xIU3o5T3AyZEdXVnA1WGNB
        SE1FRDVCbTNJZ0FoQUw2S0pnR2FJN2Q4V0JoVEpQcnlKMG1pRERJZ0VHZW9LNDV1
        ZHBlZTViakpQd0FBam9DTlIyS2RzN0lYVzI2cWlKK3RvOVV0Y2NXT2w3R1RLZwp6
        L2dPa2R1QW5NeXJVaUM2SHRpZ25TMU55c2lWMTBKOFhmTzVDNGdHczFrCi0tLSBB
        aEdvRE5HYXg4S0F3cmVCQmVvakNMSVpSUUhxcGRteHI1aDJjTzJtQmI0CrJMuZiI
        C4aLy4o3jzh9QLvppKOam00DzpHOYhxFQgQJnGKRxRdSm/6eXvGPoE0wv0K9iz+m
        7tWOCPWE0Hq+EEk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:14:12Z"
  mac: ENC[AES256_GCM,data:ZGoZBY65MlScMHp7Q8l0go5hZBfYCcYvk7oehbVaUK+aAC9mF9VVycpTgpx3JdJYSrzL/UT0DtElZFwVxMYMsa0vcmQsx8YvM4nYC1ivkH7jpyJ8q4+t3nRaodUMF73TyIICiqeG84hvb6RCMxNd7kEr3rjKNpwNwpqzUji0Qrk=,iv:0sPwtvGvQEcXRvnuMpckKvAOVZuZkN2Hno0TppHVv1w=,tag:QT2mSRLw9r/lR+7fr0qi/Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
