apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:le4YM1+5xx/pMC+Twf6PLFnkhPeyzcnGbPMgTzvHoDI=,iv:CfhsQ2YVW01sj0xGf4+quNYeL9zMlEvnwkTHBobNpvg=,tag:iLh4XYA0ruQtCuo3wVujSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDViZmtVWnFi
        K2dzUkdrTmYvbGZRMGxybUdydVNUVHZ1TGpSU2lvQ2UvRXJlUXB2dXRUak1TTmww
        bnJZRnJEeHUxWnpSQUJhSVFQbVRYa0Rkby96YUVvZWlvS0Q3bWlCMWN1M2tWMitz
        MzVQMkRoL004dzNyN0kxN1QzYStmVnY0bkFuUWZWdWpGRmMxa3VuWjdCUWpoL0ND
        RytudExkNDlmdVVJU2hoUU9JN21ObkxtZ3RTRnVjemxXUFUvRW5jemwvc2RESnoz
        eU1Da3JOSlJtQytBbjJlaFZCc1UyUDlzZC9OWE9FbVl1bTF5M2pSWmYwNmh1Nk0y
        TEtKVzFYUXgzaElIS1RrWnRCZFV4UDRrQkZaYWk5RlNacjJ0QnQwLzd2MzhQT0RI
        amgvQWlrYW5ielVIZGxjTVowWUdwaGN2NWswakxQcXBRdm5BSndoWFVXOTE0YVc2
        ZTFMM3RIYmgrYXlqWURxSHJSVC90ZkRIS0QzMXBmVHdQenZia2VRd24rZmQ0OXV6
        ZUZrdzhzNVpidHd6TGxzRzB6dVFIMFk2Z0FCTUN4TU84OERJbXlaa3VrK3ZuR045
        YmozOGtWeE1INFVWSDZnNERuZVorNnRlU3kweVBqUjBkRDZ2MVhRN1ZZNEpPK0hl
        eENKa0NoZS8zNm9CYkU0bWd2T0pxMzJ5YWRNUHM0Ni9BcXZzT3BsL1lZZVhHdjM2
        ckxVK2ZyeVRtc1pWcS9Wdkl6ZmR6UXpEU3JxUSt5Nm8vUTFnd1MrNW0vZmhpOUhz
        MVo5VTV5ajIxYmdGVXlndHBCR01udEZxMUJncXk1SmpDSmxvNEczRDUySGM4VjBo
        aDNMR0FETmp3ZkRmb3FaSmYyOEdIRHhDdGU5RVlRbUk1RjNDVnZkUzkwQmNuVVhJ
        MTNldVNIS1psS3pTL2FxclBEMEE4TVZRNjh4QnpNMDI4U2txZnNlTWI4RHJPWkM0
        NzZXSHBENk8vVjNkOE9SbjJpSFdhUmU2aVQrVDRBNTgreVhMUlJIZG1tTStCcXlN
        UFNQSEVJaWRaK0VPYnZ0NVVBcmcvbGU0RXJlZmJBa3czOGptVDJjKzNWQXM3UzJj
        ZUVxR0F4N01wYnJUWU9WRjZMUnduM2w0OTF0T3cxNGhUYW5mOG5qcXRaZzJmb05Z
        VkhCb2dWelV5K0xLMW0zMGVib01DVXR6TUxFOThmSDZtNmsvRkNXV2swYURvbjNu
        dFVHUnFTc2h3ZVlrNjRaSWs5QThqVVJTSjJlNmJwcGQrSk5yd1dUN3JLRUpwelFV
        aGZXOEFsNmRGUEcxVjBXOFMxN3czMExNbXY4QmgvaFZuT2htamF0aytONmF1Q0xx
        OWtUUkU0KzhWRkhIaFhEamdFN1gvNDJwbW9PdlJLVHlBQnZaa1JJNmxoSmtoQVQ4
        REl0Y0RXL0pUOUdhaTBZQjBLZGVtdzlsMHBHTHlIdnBNR09iK2NOb1puWWVKLzVz
        NDhxRUFlQzFFZnltR3kyU1hpRElBdDYxdVBBVEw0azFOdm5oUm4vYkpkdnVJYU5W
        S2VHRThwaHRTRi83RVlLQ1NwVU5aQ1JPelcxZXZMRlJhaFFMTm4wZ3YxYmdQZkFl
        WXd1c28zYlpVWnNISWJXM24wZFdHamwvVFBpamQxbjREUzRQa1h4RkFZVGFyVFh4
        S05SaFlBRXNkOERQb1pOTVBsS05wWndWK28yRWpTSjZ2bTcrSUFIVE56ckhhZFF3
        dWNhd2ltQ2dacXZEZW9SbXRuWkR3aC9IdEZVc3ZiV2RYaUtNd1JzZU11NU5NVjR1
        Zmg4Q2w2Wm81QTBwbWRWdlQzVHJpRlNvVzBsb1JDWHdTL2RqL0dtZm11MmJmSGdh
        VFZpak1xUHd6a3JRYk81WGRla0JQYUpRaG9Xalc1TXV5Zm4rOGtZZXpFUU8wb3Bq
        eGdWUXoyc2w1OWZnaGxoL3FkU3dncXkyQkVhK1pFUUxFL3FtQmxBblQrQ2hRZwpm
        WkpJNXplZExQWDF0RXFRajRTRjBBM2owUGJNdWUycyszM0VvaUJyNkVRCi0tLSAy
        Y3hFVVFYakE2Rm1NaUFndVg0dDhTbjdaenUyMmI0R1RpNXZILzZWWCtzCn9qUgn9
        kIF8MwZJ30ALhF3fHpsuC65zhGZNm9PGbAYCAeHOeiAb4y+jV5f36ahsfW0h8ytW
        8xGntkCEiGWAd58=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T19:42:02Z"
  mac: ENC[AES256_GCM,data:w7Gf9w4JQ962hXUcnnqujzOa5JS3pV1pQE1AYGu0y/kiJzzt0yUX3SoISfHdPF5qeGpaLWuh7rVCmrRHM0k0DuX1voX3iO2KaAQU9YzvXYKuSEHUjiU8Z7yfHQpkA4WoA+N08I30YnLsvLJ4KfmBHcqarGmT046uY2dTYwxXy4I=,iv:W+otCMDOyArhcHUcCMEagW7OugyV+BwEkFH6U/CsCuk=,tag:mbusw3JnicJeQXKuOOzjNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
