---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./kopiur-repository-secret.yaml
  - ./echo/ks.yaml
  - ./plex/ks.yaml
  - ./jellyfin/ks.yaml
