apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cXUCI0MdX/i23VO582ZGbfvQvqtdcEjHOrVQoJ1+tlm0odR2NT5bDCFgo9iaW7BpY7YQLmRrtXyQU74eNQ5A8mIkjtU7Bf0Zu/cgnL/8Y/7KRveMfG/shK1rAQzEpezfNHA5AhNO1FmFbUWe+GlVrhsu6ZMgXZv3RnZ2cKzrLZF+aC8xWd2z6v7xxEUYz+WBtbTmVcbnK2g/dvi7+akLFRfhS3PsmlN9+MYiNKgbQ+KFqLYo,iv:aDiKXZFkPGK2Ajwx9UFLct9zwF2zW/4wdnbP8TR5RKw=,tag:lKb9184Nbejn8UaXe+vP/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGRqeFZSVElI
        WVVwM3IvTFRpdVpkdUY2MjRJTEdSTXZUODlmTENja1UwVldZendNMkdJZnJwRU1x
        VzZYQ2UrM2RzdkNaTWdVSjc4b2hOQTlTYXl1L3p2eThsMWM2ZU80ZFVBL3lwWDdi
        MTVTUDNqUHhURHh0bTBCNFkyRWlXdzRJQ0pKS0tuT2JtV1pTQjJrZGhRUEpweFV2
        WU1SbE9qMTROVEpMdXFpd1MzQjFEY3VNeHFZMnpTS0REbDYrSnlreHBvZEdpV0Rk
        Qjh4aGUvRjFlNVVLcnV0V2RlWWZvbXA5eU1mZ09UcTFUSGJ2UzIreks0dGdCVlpr
        QjVkbk5JSkxFL2UwYlEzTWxRS2Y3MzZSbzV3aEc0VEtIeDNtU2VUWDVjZXF4L29B
        QnpYNjJ6SGR2NEdlUkM4MWxtZno3TklLTVFBdkZEYUM3SUFWWEZHZDVoWjhGaTR1
        bUgvWTE2S2czK011QWxmNmF5clVPNHZ6ZGlmdE9Hc1hYV2NpRlk5RVE3US8rY0hp
        dWhnd0h5Um8xM2dRWlh2OHhqRFh3Z3J3VTQyYkNQR1FncUsrRGMvTU1YT1hTK1d3
        aS9JUHQ0TmJEMWNPNTJ5MlFHT0svOUhCaFFQdWNSdTJzaVhteHBVenNTbTg1clNw
        bW5rOHVvd2Q0MWR6YUIxU05zeHpab0xOUnZVWkFGU2YrbWxhVDlQOHhXVVZiQW9q
        SFY4b0dERlJSSWp1L1YzellBSnErZDY3TjhDRG52TTJWdW5IMDdBWTNSa0hGZUJT
        N2F5eTZMQ21ocXp0VEUxdHBnZGwrSGp4dEN1UlNUbmV4OStLMlMyK1NHVDVLZnZm
        c3ZmR0FDY1ZrL2FmMHJFNXE0bW0waFNndFNFWkpVZDBhRHJkck9MaUhGNmVvanh4
        bFV1VHMrTXlQTzhudVRvZUxiNlp1bm55TGI3YS9kZTRmek1VOWl2ZEtZQ2wzVzl2
        bzk0VjhnY3ZRUUlwaVptLytWK0lkTDJ5R3pkK3NRSUpvT1ZYOFAxQWhxTGMwOXlC
        RVp6K21OZVFWREh1cksydlh0WDRxcXBhRG9RYXZNSnk2ejJPNFpIRlVMYWcxQloz
        OFUwN2xWS1BSRm1EeUw2WXBzN243ci9QeUF0OXQ1TTNRbExFUldYNitTMmxpSTdF
        UllzQ24yQ3E5LzVISmNSVnc2eVNaSU5RMWx4ZzRla0tYUys1YTgxeHJ1blF2UEM4
        ZVhKNEFvSDNJWmd6MWhsNmJ2TDVvYnVoYng5TFZZOXNmS21uMG14UnF3djNuWDg1
        eCtvTkNnOFdTb0ZqOFFlMWZ6eHpjRm5Ib2xvRlBlaEFkYW8zY1Vzb2xkK0VXMmtZ
        QnpTWDQ2TGFGVDBTM2hIQWFFQnZsaDRDaWM0WnlnVHpDaVBoRTRTbXdFV1F0OS9w
        ZFpoVGVjRFo1emVQdkJuSnhJTzNKY29oajB1NUFzUDZZSVgxZXpzK0RPaVZ5TzZB
        eHI2NWc5ZGJwUkhZQTRjSHg0dkZQTyszSWtVK1hwZGZ2aXdETWlUR3pra2Z6Q0tD
        Sm5VMUlvWkN6cjdiUTRNc2o2VUdoN3AvNGNPYmZtMm9KbU5xYmZwUFNpOU9ISzMv
        RUh5aUw1WWtmVEdvRmpDVG1sc091bEJ4U3BWeUs2N1d0NnNhZjFsZ2ZEa1VLNnJl
        N1BrYTZpdUFseXhtYTVDckZjRU4yNFBDWmhuYm9BUXl6V2JJNklLZldDUkJqQTEv
        THgyVHZSQ2FoY1RlQlRuSkNhc1hEaDVjSGRyVUpkbGg2T1RwOHNTN2R1TVhIRmg2
        ZlRXZlkzVVk5RXhDQ2dEcjZBeUlwaWFsOXZOTXVnK1VwUzVUN1k3NExsUmJBSEtq
        QXg1Mm9IVzJhaW5ObVA1cW85T3VmN2xqaVdOSFdiNjB3dXBWRzhWWS9ySm5Bdmha
        cFcvd0ZVdTFCVjBMTEY2NzNHK1U3cmxseTJmTjczMVJRME9EZC9YR1IxeWNBQQpM
        U0hUMDZVeWpSenQ5cGZqTFVDa2ZDMXpLNDFlaUdzcEpzWXFIMVUrVU1BCi0tLSBT
        Z1BVTDVCRzN6TzJIMHlJNGJ2aG5VL1AvaDkxQTlQLzB1TUxJSnZpZmQ4CpYXRvPP
        GwHV5rNrs8MH9/e9znRDpmYQf7QMH4Lay6+LoM24cN9M+UFiATmQ9ACkkqacM+6a
        pbD/7vYsg4W5pjw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:58:30Z"
  mac: ENC[AES256_GCM,data:MZW446ymcC2z4IW6JLC4dcYajhn/cbXrB2vMqMJlzj952L432ZPnfFYlEk+Au6HicvokbmsILJiORN85l7CpZZIoVL1lfr1sI+lGj536jvmKfsU4X9+edwutFqkF9QIK9ybPYoC+U0OolTmtraAZDPgU5M0iaHEawLSCprNIfSA=,iv:xb3c5ouiMizaVH8epRw2CYmwR1sDu7DlkUeP07sn7jI=,tag:qoB5AdyYcbRRwvckZ0vcHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
