apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2HxmL9Uq/9pYNsJm+sGwm065LPiFbTIQHyZeUlb2AmqIoORsivgz4wkxaWtJoJ9GWpCfWGU110xNimq7T+yFp+1CNWU8io2p4v23Jc0RgGRGzUKAPE/pfqh7cVOvHekcOCcQImnNzzV4Q2XpZSO3CkFykrJcnQLNBDwMQhULNbTclvEtB5RH5fb/pGZOOeEWZRXqUrlkxh+O8z56InEaYb4lqdtWovslda3SdI3U/U1Pq6/g,iv:OdHvwVFBpzGN8jut6O7T2UdX90Kh3VnLRgfOCfMqGd8=,tag:z1TR3tFC9vQXG1hDK8a6sA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDFJdU1mN1Ba
        WlQvSHNNNjBGRkd6T2ZubzF1NHFJOHUxUkgzWVU0Z0ZMS0hTczgwY2xOMmlPY01m
        WkpYZ0hGZmo5T1FXSDB2QmlPSFY2SUtLbDZ0MDNTYmZuaU5ZWlBYTEdZMWkvK256
        OHdyTVA4S0dBeXZJUWUvU21YbWFUanY1dHpzaWNYWm1tRmN1eEZFVExBMnVjaEZX
        ZFh3VnhTbEJ0TVZJMSt3bnkzamFwS3hmMFJHQ0FYQ21ZK2ExdHcxZGJzUzZaNm14
        ZjVkamU3UEdGd3YxSGJoN204VXB6VnVCeGFSUUhVQ1k1WTlPeEZxbmE4TmZLWXZV
        OEl3STJ3OWZsWElBTVIvTERTSXl2NENIaXhlaFhHRVJONDVNRWRvYUI3TXk1VStl
        Tmg2SXZCbnhEa2dEdzBVdVF6aTFpTFMzSEZWaTNxbitSRTFLVkt4L2ZMYVl4dFRJ
        T0U5OHVNOHZjWE5lZ3dqZS84SklKVzVWVFJsSW1JcXFmdXB0bVYvbmhFSXZUc1Ix
        S2tiRzFaVnR2bHlFSDZaME9iNTJuV2grOGRBblgwTXJlYXJDTVcvbkUyK3BpbHlO
        RlBJVEJMMkptQUt4RzcwWnI4N2RFVENNc3Zrd3BhYkpONHI0WFZUSGtwR1VGbnNv
        cjJuMnZ5b3g0VGxqVk9sQUtEVWY3K3U4bUx0MFRsODZIQW9vNFRrSXdwYm81aXY3
        TVkvMG90QUJ4M2VLNEtHQmNxSml2UG8xMXBNNDI3aldlUlhUOHdmOEhTbjh4Umxx
        dGNMV1ZxWGxEeUg2eG1iVTFwTFZRcnNIV2VhaUdZdi9VRmhINURUMy9Hc05LNGhO
        YzZ0citYQnRIR3JGTU95blFRdkgxSmxGR0k1ZmtDQU8ydlBaaHFqR0ZJSGVZd1NR
        TFFWWEVtZk5VbWdJb056eFJYZ1NtZUVaMHhJeTdTcGp3VktxbFF2N1dXaGR3UjFL
        R0JTakl5R2FuNVRGaUkyNk52bCtmMUoxeVVPcVdRQUFGajFpNFI1V2RxTmJOTU1j
        NFNrUlE2bFVpRnlSbGRJT3pDMUVFKzV1c3ZvbU51Ti9VVVprSWRRemF0cVRZWDBI
        Z0Fjc1puMEdId20wL0drSzVJRTU5SGxKbHFFc0Z2emQwVDhmVVY3cnZ3bXBKTHN3
        SlQ5M0ZGbVJ2Tzgwc2twUW9tS1ZmL3NuTFZtSjBxL2FKK1lWY2FZbkQyeDZsSWli
        WWF5NmttSDdlVlcrVmhlM09jT0dGbE12ZEg5K2tET3FQa3VremVOanNPMnZRRGtR
        RTdTVVlIS0NoQURyKy8rcWRJcWkzakYxZGVFVnoyTjNOZmFrOWszZlRRV21vaWJn
        UUpxUkhkaGovMEl1ZTZMMGdLZmdkQUVhRFZBT29nTXUvNzRzMmNzb0tGT3NVa2hz
        aTk4ZkphVTRycDF0MU55bVBFN0hST1VxSGdoWSt6ZW1VWERFNHhhd2phdHVHVlhO
        cW5GTlUySitZdk81NlY5QXdnQkw1b1ZOcDdlcW1CSjV4VnNlbVVRV2wvQnNudFRs
        cUpUTVZwMWwwZHpHZW8xZ2Jxc0tBYjBMSGc0WW4zWUY2TmtZRHVmNUozUWpzaHhY
        b3JuaEk4cWtGV0MyNW4vS1lTZDduRGVBU1VNb3VBek4xaFhGdWJOOHRSNUJJc2N5
        NTl4MDVNYVNHY29iZVpabHB6OGUwUXhWdExEaXBSMVNxdy9CSlRLWWNRaVdlVFkv
        YkJHa3FEaFdMSE5ESHdraVM5VXRRckZCWGRQQ25Ickd4L0lKTm9ZUzE2SE1EdzBM
        ZzdoL2tITWVoV092UmNCMnJVdDcrNWw2d3p4enQwUzRwSVJCZEhHTW55VGN0Tkwx
        bjVEL2E3UWNIbS90YTBrSTkwaHFqQVJaZXNKbHNNQkk3WTl2Kzh0SDNPZWNPZ3Vh
        bU5nVHdWWnA5RVNYOFVGU001UTZrbW9DY1U1Uk1ZMnc1UUhGZk82QW9sVjdNQQpi
        eU8yY3o5bzloa3Bpd0FkUU1ESUpCcU1xVElPQXkwMEhtYmU2YnVaRlg4Ci0tLSBV
        aVluSVdxWk5BSi94Znp4MTFrSmZxM0dLOTgvY083UzJKalhFeVlaQkdNCs2aQOaR
        obp5W38zgBUhUSHeXlAfdcBJLXroY4KsWDl3n4JDiO/Lv67pQMTue0vjJq+r+oYB
        YagHPA+6IQbqscA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T19:42:02Z"
  mac: ENC[AES256_GCM,data:MddfQzaUkVV7r/nupOi9SLtNxURPZfUX9vsLiwKvnzweDU3C5yBM9ye7/B55dE4DA8900RXZxWAGhvls/patXPd9BDM7213GePuoIoJgBcTA6ds38uNNUIYVl2vYazDBNGjEJmRl0gofWELtxEQO/EZ9X/5UTSdKa9yvCIDRK68=,iv:w+930Sx83IxCzC1k7NGim+v3xir8jSj16f9CKZllnXE=,tag:HnkNu6ZKki8dNfmWFElW8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
