apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ftcCLWAmzsUhn/AkBCb0eLKSu/xC3Zt9MEhMdm4p3ukNej3G20ioJXTcTYf2wCLmy6pppuC8/rThAdgXyWfkzLpbSo+Pga9joeJhgX6P7D3+5EmNiXIIS5Wu5a+kIKncjEo3yfvHa+LxCKFZddjNrpYOxL+wWRMKEpjP4Xjk7SFIZm7omaR23diYtgWz2oiYjJbR5rGvTrLzH3a8GQV84/AK9Ltz7VaVsSVIFWl/WeEMYyoi,iv:t9cd1q69EgA5bsE6W8HN3tK81SW0SKCVOKD6NRcSj3w=,tag:pmJU7H7drwUuT4EAULVg/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEJ3Y09GMGJx
        aC94STRUV2xJdVgzUEhWUE95eXMzNXZRQ3JWemJmNFN4aU5ycHVodTJ0cFJlQzU3
        Tk9xWUpUQiswNi9JZ29rd1VObXdRam5GSFpKK3MydmkzSGIxMUFkRUc1T2R3bmVz
        NUhNbUFEKzZUT3lOS1hBblFic2ozN2o5dTFaVjNTVXpaOEpVOGxCaWN1Z3RnaU5h
        Nk1JQldrdGtVTGl6bE5OOHJuNDlldmlQT3VqeW4ydWxiVERzL3hZMktIZlZ5ZWNh
        YlBVUm1oWFhIeXRrQTZPdXA4NDFZd3l2R1NQbkRhdC9QdG8yRENXd0xTMnkvTG95
        YWNoWnZ6VXhtM3hBQkNkSnNseDRHdmN0VU1Hamg2U3lqTURheVBiVWJKNXB0MFc5
        T0srSEsyalVFNWc4RENxR2U4MVhCOHpxYnlKSEJaTEhzbUxhZ09NM2N6VFNKNTB3
        YkhNZ3NjTlhIcDB3K1NxOGZPQ0FQdElCSktvaFlwYS9XS1V5ZGMvQW11ZlYyYzZV
        MnYzdVVJcUNPcWhxUjhRK0x3WnJqTDVuODV1M2JqcS9kK00zR0hkbVJ4WS9idmx0
        alVJK0V1V3djZUtUUStLVHppVGo4VXlLTGtGSkVNRjdBclU1NTZnV3lqbTZ6QWhv
        am96YXhEbnBVc1JVVUx0V1hzZ3RkWHZDZ05tVDNaYlN4T3VpUHlSeURMd0g2bjk5
        OW56T1Vlc2t4VkQ0ZTZiN3hMVzVGdnl5UUw5Tko3VGZWMGlmNjdDTXBHUEgrYysx
        SC9DUVQwVG16SmxzN2MyTjB2VDE4TkhJckVjb3VlN2pSQkQzOTk3aXVXMFVKQ25R
        emVOdFpwTnNQTm9oMFFFU1Qxc3E3NXRLL1NEVThFMmE2dGwwK0x6SkN3RzFvcWRy
        dHoxbnVDcU05cEl4WDd3NVA5RXRzUVVJQXBsQ0pPSEtkLzVzNmU3MmVWblNFQUlC
        d2xnM0FheTk3Vm5KbHEyNlFyckl6Qlk2YmdqYS8rY1NNbHlGMEloRlZoTWFaZEhH
        OTR6c0Y3S3AwYzkwdjRWTkxtQ0FZZ3VmNUhieVdEZEpTZzN4bWphd0VTOHR5encz
        NnoyeFVaS244WTQ0OEJFQ3N1V3ZDN2tuc0gxNUJITmoxSjhDNTVPaGR2aE55Z3Qy
        bk5JUnE3NW9mS1gvWWZkTmhYK2cvY2dRbWErVkpVMVZKNk5XV0xkaXNSdDVTbXEy
        RzlOSmEzbldrTGk5RkRLOFh1dTVSMmdyNG5hV3JaQ0haMmxYdkpUL3BZY0RMajJh
        T2RrbGVRNzUzZXNrTmhDV2VGQm1LRW1IdTUvVWhjd2FON0lEM0VtSFdTd2tqendV
        a2JnTjFodG1zZ0NOZTZrVmNiYWQvV05GWWx3UVN5MXRlUzBRdkFNcytBUG1vbmVP
        WVpVUFMvblE0WlBPa2M1eGtpcUpucVhqRldOOHZEOXBTSmc0QWJjb0RDL1B2RTU2
        Zlh5YnAxRlFScnltdXMxL2Z0RUZiTTJqbGVlVElRTHBxL2FTd2JqT3JPZWgyUURk
        Zm5SNXVOeUgvR3A5VFpFaGRVenVjbjVxWVFlZFFibmUrTnpkZWplc2x2RmMxdTRC
        Y1pYakVIOHVYME9PQmxRQ09kU0dkZGgrR2Vib3kzdHV2Q3lCN0d4MFFXOXNuS2Ry
        UmcrWFlTOXZMZ1gvbjV6NGZPUDRqUnFrbzRMY3FENWVnODU1bEpwZVhVNTJjZWhV
        M3NacTAxR251bGx5TGdvTmhpcStTeHRTK25QR2Npby9xVm9JbXBjQmJiNDJRcDls
        aEZrejZab3g3RkNDQ2M4OFA4NEg0bEx4YjRRV3dRMDJrVFFEOHRVQTNNWVY2MGtz
        dVVNWkhHU1lRdWlKY002T3M5dVdMREVlNVJpV1R2Q0U4VE5MZkhWWE1HWEN1bjNC
        TS9hNU5CTVppUHBiaVFPcTBDaWtObnRJUjhwUjM3a01EdjcrWHQzSWlMUEVJUQow
        WW1ZcjBoQUMya3JwTUlHVDQ5Qjk1dWd4cDR2bVhRVVA4UDdnck9JZmljCi0tLSBx
        YkNsdEZPbDVtaGtySFNRNWF1bDVJU0ZhSjZwdm5DeSs1UDU5WVZleWNJCgdOi9t3
        Lu6F1LZM/mVf5Ud1gt8JBFhSCcmtiw/BOaQRpQvYJoITACGfafrqMLy61ft4O3S5
        kzk08l/8FRE8q3g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:19:53Z"
  mac: ENC[AES256_GCM,data:BlEvsN95HF7ElH5onIiKrIScpfIBDnIWc15n4notwIQ3pTMMuiJcry/XvbxyYElpRhwxHWV4B6esfpQFVdZktSaEWZAhASPj+zqa2pdaWj6b8dF2xZypnHMi0EL/nGmF7YFOhJzsEKcr19H/Aq9JBMqlLPTzkF0YiR4oREiD/vo=,iv:zc0BiXmx1DMn1O6cHhcsZLiUH817Enx6d7Rvgyw7EYc=,tag:D7XsAIF3QArtBcel2ewiBA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
