apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8HfMG9/SpxcyiLK1Xc0XFRwlwqFb4PLyQhF7Fkij8bLNtOpSezZl+h9A9bmha6Crkg5yqw0=,iv:OECtPHYUuosymTl3EAl7KTnACgLFf49lhoNWs9xUECQ=,tag:gLLXcQFttl1IZrU0q7lmxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNvWUZ4cVpi
        ZVhuMHN6QnI1WlNxNWQ2Wjk5U0ZmRUk4ZUlZbUJ5Rzh4OGRpdjQwWXI1SC94U0Rq
        UUVLSXJpdDhzVVFWbzBWWVN4MmRnNlF0UmFXWlVMdSt6YlVnMGxSR0R4NEtTaHJp
        alkzb1prVy9UUEhXUVY4aStsWC9oNWxXRkkxc1M0ZjQwd3lMOHJaRjJ5UURQMkZS
        ZnkxVmYyK0d6TG5zQmx0eXdVNG5EMktUdHdVcVhRMmNRK0FwS0s0TUpKMVBOZllr
        SCtxbmdPSWN0Y1hsb1ZQc3ZiSVJlK0NjWDlLRWVkeXVVc0pneTdwNDRNM29naDBt
        bWs5S29zVlFCOURaK2NRVVJZdE0ydklXbzlYRnpJdlN6VVJOTTJjbUwxR1VXOVpS
        a0JXZnVxTVcxZURpN0pHSUVFeDhFd3o2V3pNTXdHM0tJZFVKaGs0UlY5YTZJWDlX
        ZWIvdzRTb1g1NjdqZTRlNFd1ME1YMW94RkVRUUY5WURTQmpnd1dxQm9oWitUT3Nm
        dEpmUFQ3Z0hVZkxZQ2o5eUhiQURHUytwNUtmajRDd0x6K2VtV3ZSSVYweG5LYysy
        a3FhVkJrZnhWQU9mRWYwMGJ3SFd4V1RGTWFIajh0MkVjWnR4RmpXNm9Ib0h3a1p6
        MFRkbGR6M3YyK1FXZ29idmt6VlpzMDRQRTh0REZSRXY1dHJLbGdtOWFSSWRTYVpz
        N3VreE1DbCtnS01GTVRmRHRubXFDdmVVVTlBNEVtUzFuYVk3dVNob1FLWHJrQmdX
        OG9kckNnOWhWRzFWQVo3aHgvU3ZXN2tuOHJTZW1LTldvUVZzN2dvUFZoQTB0UWhh
        elJNVUlPbjJZOGZ0c20rMFRtMjlmb2dYT2tQTHNoWFUyRE5RM3RjRTI2UmhkKzl3
        VWhGbXR4OHNndk0vdDdPeHlYOE9OeEgwbDZRYWZsSDJLaVY5TWtNSnFzb0ExbU1i
        QTVFb2VYYzRVUDM0OCt6a2g5S2lWT21ZOWl5UHlrWGhTMUJUTTA3d2NJakFpVy9t
        aGFsRktoRFZFdzRPM2owd1oweEpXb013Uzh0KytYYlk2NysyKzI1dnFpNzd1ZUZ0
        bTRBTmRTVFBoUDZqVW5rTVBvcXJUZHJIUk9ua1ZLVmFjSW5WQ2w4QTR0OTdKeWlG
        VWNROENGWkZ2VFlpNE5kYXVMODUzM2IzalNOMXU2WVFGaHpwRGRnazYzL3daaElV
        UEtxV0tZbStkVERFa2kvRGw2bDVrV3VVYnRrQnd1OUF1OWFEYTR5UFNraFF3KzFX
        S2VtV0xWYVY5UjNEUEdpUHB1aHE0b0htWjNpMlVhSFZ4Y1VibUJJaWdXcDB5bjR4
        dWF0N3hCZmxxS3dCM0E1dC9MZnMzQVNOSHRNWW00Qk1QUGloNnFsMVowOW5OelVI
        RWFFVXVidElIMGtNekZiTFdDdGF5MkJ1aU42YkVLK1h4UStCWDYvV3FKeXp6THUr
        cFIxaDV1S28xZXdHNDNVQUpyRjN5Nm04ekZ0NVBMNmJHUnorT1hYNW56SldPZytz
        Qzd5Zml6SU55RFdmRG5BS3VId09QMXRlOUFkL3k2N2NYVkhzRXJhZDFFL2tVK3ZG
        L0k0YWRXSERUWWppdjBCTE9ua0Y3WnllVldSbTRUNmQ3YmFYaWpvenB0Rkg4THds
        VmJHUHEyYUp3Uk50YldBQWU5bEo3a0RidGErYldrNEthYWYvN1VNWHFHV0FrV3RU
        TjFBTmFmK3BycGRyOHJxYXcxSnVIczg0Yko1MkJuTVZoRFB2alcwZXdvdUJrczJl
        YTdVZnpOZ293TFNpMXIwd1dsN0JQSU92RzhYWElDVElpSm5SYWlpL081Y3pldzRT
        Q2tsQWtBZ2toZ0dQY2V4Y1lEdVJJQzlMcjJSWjFQeXBtbDlKclNWOUlkYlFGbzJF
        cmsvOFhrQmtqcGUwVTg4enNhOHA2OTBIMzJqL3hzdnZPT0tQSjFKcEE2aEtMZwp4
        UkcxbHc3aUFtWE9CazNrbldGaVh4OGV0U3lxQzNEZWxycWtxdkM0Rm13Ci0tLSBG
        d0k2aFF1d3Z6UFZwdHg5TjRTVVM0RVR2TTRrV0tFalZWcnlDVTJqeVdRCnL2Wl/X
        vNYZMOiRc2Olm1huBYa8rcivxV03MUJq9dvBFY6cjerj5qB+bpBo/cBaJdZlR5tr
        S6O8CzNW3hO4vMg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:14:12Z"
  mac: ENC[AES256_GCM,data:A2gKcYpVyehqobf2bfQIUEJVRPVoDdyt9ZBmDCCznB/Ioh+imfosLDh9tw6gBORKwhJ1qdi8ZUnadsQJ1irhcpEJ//BdL3dMpKii9Uh1F7eHkZZb91FOiBu8LopJXBTCgAxBWYJjvGkk95Z0zGt9bKjGG3BBIc4a9i2wsmIPdCk=,iv:NOlv2MMEJDlpIv7We2NptYhS0N3EFz6B5Hse09upMb8=,tag:BDuvb7ulU90ahFs5WWFcQA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
