apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:G9ruC0UNB62jJ94U3MVBvOanrVoI+laL9YuPbzgAB+5p1YspVC8Rc4S+h5TtITRH85ah4ic=,iv:dLtWnNVEE1CHMW3jyD2U0pEjbopso8IZHQAFowXTOxg=,tag:Ucr/wt7GMzo4nxfdxuAh9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGRrd2srRkI5
        SkNScUtENFRTSjFVYStQc041VWRJWm1mNDFJR1U2c0xTRDU3TEdyL1FqWnRkRlkz
        cm9veDJuYXNrK3NqVmROTVRzcUhBeWczR2ZwaCtsNmQzYVNMcnA4RTlwZXVqM040
        OERsYkRNeGJmZC9Ic0tvTmUwbzlpcWoyVmplNEdxbGJINjBjaXdQRGluZUFmNVhy
        cnNXWjN4ckc3cEp0VlNBMTlnNHlCaVdwUnFCKzUyMmd6ck1aMnNOZmx3cUVuNUZV
        K3AxOEdKQjhRbWpOQW9menBpeWM4ZkxrWGlXU3J2SWdoa1ZjbERUa0hDcEY1K3hW
        Z2RxYkhuVDB0clE2UWlHSjBvWjA3L0o4ZGZMZkRudlMvakUyRnJjRUxIUW8wdDNG
        b3d1UTNIUk52MW43R2ZZNVpUamJ5UkRiQVZDbTJaeVAycUhmc0g0NWwzQ2NUOTFO
        c1BQdEJqc1pRcjJuQUtuZ0VuYjNuOWVDQmlRV0RPZkFsK2NoaWUvNlNCdE9IK2c5
        Z3Z4MjZleVNNaGJzbnN4dHZCVUV0V1ZkRlU2TFFheE5HZTkyS2J6clVNNFdKc2R5
        dzdKMC9tS2hUTVNxaXdMV1lUL05HNzBPS0NPOWdWTEl2VG1JcmdYeXNaak5XOVE3
        OHJqdGZpa2ZzbTlMYUkyYVpEaXJVT2FwTjhWWGNhS3ZOUE9JMkdsK1BtcXY5VStX
        L0oyb0ZzYWkvbWpGeUtUMm1rMzFma2l5VitkSTlCaXFHOVhFczdRVVlNaUdvQ2ph
        cFdrQmZwMU1hWnZrb1dqZnB2M0MzenFrWWF3RDFLYkVVMUNURmU2VFRyVlVrRURS
        anlkc3FVVFRWRnpCVWMvTk9qNWtrNXJYbnY5MUMyeFZ2L0NINWI4SUNaQ05sOU5s
        S0xMN3VCVkowWGVqejdvcTFyTHpUZGhnMTROc2Z6dnBxYWNoemRudGpqMHdXQTlt
        OW8yajY1bmRURms1S1NETVl1bDdFRm9GUUxUNE1GcHdiTklYQTBEL3UzTDdnaEVO
        amhqazBUU0ljQUMrQmErbVRCNllvV253bUFqV2ZURU9WSkI4K243cEY4NVlRS0xu
        Wm1rb3Ziekp3MXdwV2s5eEpXV250SFUzV25oMFdvWExjY1VIc2lqdk92SFVNRGJO
        K3ZzNm05RFlpU0Y4MWt2UDN3Zy9HUVB6Qmh3dXJwQkF6MHNQOFNjWURQaEI4RDBx
        dUpEcHR4M0k3bG5PWEttYWFOaXhGRVpnNHVvUEJJb2F2VGRIdHNEQXpLMW0rV01v
        dUZOd0krMU5oajdrQm4xL0ptZERmR0M3Nk1LOHdiNGRUeFl0bVppRHZrWXdCQjNs
        MUtaQzJCMkxJajlKUjFkQzB4cXNQU2R5RkxMQmtVQlY3YkRxNXdndE1NaWxYK3VN
        UnRSWHo1bTU3cUY3ZTJRU21zOFJ0QWdMS2M0a0tiamc2d2N1cEx3MTdZZWFNK1dq
        eHFFL1RvSGc1U3cvUi9qVm1MRnUyWDNseUpHUWxrMm5oMStWQnBxUDMvMlBLNzhB
        ZlpzYzh3VTRPQkNYR05OaFdMWUJpeUxXOW02U1ViTU4yR0Jnc2tFdFVQM2J5elZD
        S0tVS004Q0l6aEF5U2UxanBTR09UM2F4dGlsaldZcUE4S21PL2EvN3dZZlZwK0g1
        bmZ6NEh2WkNMZDJDUSthTEV4b1hOVS83ekVRWEZIMStIZ1B0aHNKSEVqUGIyZ3Qw
        bC9WWktNY0kwLytSaUZFeUZmdjdtcUg1NDE2ZWJIRklXd25xMFR3d3h3Smo1czRK
        Mnl0TWN1ZnhDNVN6V2JWc3pYUStLWTZvTHdBK3JFOEFHNXhUVGw5Z1pqaEdxRnNY
        eWZFSkpmc2xIOVJ1c2x0ZlVmRHRaSEVYMzM1UDhPMkpER1pJUWlPR2JoY3lMeW5O
        OWpOUHJQYXpUZ1RMem0zUnB0V0lzc1MvaUc2K3A4NktuT0ZVSXZRU2RYbWdMQQpT
        eUVkZkwzRFFlaU1VY240bVgzb1k0dXd0dVhPOThtelR1RlJVd0hvR3N3Ci0tLSBa
        UkEybWl1d3JPc3NobkxmVmE5RzBSQXR2U2VMaFhtdzJBRVhxQ1EyQnVJCgqYSB8Q
        tBxPQl4f3dbgFjnC7scYklXV9tUkfqWZtUDUxpH+7v7nHG3qX8oiX/vxtF3Nn7Zn
        t7rXSqJLySOlVJo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T22:58:30Z"
  mac: ENC[AES256_GCM,data:rMUmvSU7Y+WGybCk7eNuMACZt6nTgjS+IfgZ7dyKfaihRp14K+sVnfOaK3HwyhLBAKQl7fhHO141wkU3x8aBnUjjTZlelES3lCM8Qv5TEVkJmMLw8NXYv6cJcza4I/4HylolvxhhgzuDsizBI7UvqSPkJiwDai0vfW74maP/dVo=,iv:PF7iRkonqnK0GEk619roQpNtfuCECUhQgW9O+daGnYo=,tag:SDoFD5Ztn4l1eEGc6cvJHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
