apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0K3iIC7ZmnOnhYZIfIo8Hq6GXwrM76Gk25DWiJiZwF5LKQE3yIVOYvKaPpj8HIMxclqqUXA=,iv:lb6FRYZhyPcF+D+S98u3kOI0pr7AwJTnaSXXcQvYoOo=,tag:O63bIMy8bdJYbeFcogSCDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBxd0xydjE2
        cEE3UTRxbkJiT3NuZExURXhxVzZZb2Y1dHRVaklwTU0yWkN2Z1ZBV0xSNEJDZnFj
        Q1FIMloweVA3ZTloaHZGbEtvemlya3NFZnF2QkdHWEZpYmZzUDVWRVlYMGZDYW5V
        SWNGSmxwMXRNNm44Y0NZcThCKzUrTUR2OW5MRkFVNmFHMWRTVG9iR0JlT3d3MzB1
        MU1wQXh2V281VmR4M2RqaUxHemlFVFZSQ2hNRUNqQ0VCZ0NMSVBCUmtLQkpzQXgv
        RUgvTlAzT3JLOU1pSG15MExxNmxuNHNOai84MjRzZ1BRU0Y5K0FkaXM5dnM3NG1W
        NzhvejdEOG9vT2M2UkRWbVFtREpxR2xWTUdBQTBSQVJPWTZabEg2eERXblkwMEhS
        VG13RjlUTjhNYU9QUTR5RzVkWGRKbkRncUNZUUJWU2F0eXNuUXNKRFJ2MU8ybGt5
        SndtMjNvbkdhb0NkUEEvbjlkQ2g0ZWJRU09WMDdRQmRQSjVEVTcxakM2d05OaHNr
        UkNuQzlSOTd6ODN0N0g0SWJ5Y0RMWmFQbUhtZk54ckdVc1l2SFpYc2Z6ZmdrNC81
        QUNPd2tXOG5tS3ZkaEVYOSs0cEhQN3FaN0NXUjNJVE5yM1dLTWRmQldTK2IwcWRH
        K2tNWlh2V0J2TlA4QlVsNlVsOTlZTXRkSVJ6bU5iZloxcUtCVHFiMHpabWVMRldt
        WUY0TDBEV2R1TENvd0xuSjQyQlZ1MjJmZjFCU1k1WUYzeThGZXdVeCtCTXBWUWdG
        bStxZ2s3N3dsWE56bWxSS0VFMkh2anRoVUU4NXZkY1U5Q3VrUDJ4bk9uY1QvNWk3
        RUlWUGtRZ2dTcHJCdVJ3SmpjMktUbEtoSTZjVm0wVmVDNW8zckdwbXRpc2JRbEFX
        Qk84YlQydE4xWDVBUzFQY2ZQRVA3OWJVT0xxNlNmQ25ienJTUGV6ZWszOTJTOUpN
        TmtVOHc1SlB5MnpKSVJ5TGpkanRPQ1l2UnhESVJCU0JlWkZGbW45L0VXRmVGRVdo
        MURTUGhHQXJldTd4eVZBUTJrVkpVOC8rV1gwNE1lWFJjTFpkbktHcG51UkI3R1hx
        eEtJeC8xU25LN2YxSTdYOTdMNy9CQ3hTMkRNZ3J6eW1jaEhlQmtTWng2TG5aZFJG
        eTlZeC9DbW8zbmN1QTRPSVQxZzI0TnJEYUo3M1d1cTJ3aVhOUWs4bGs1N0V3akJ5
        aU1yQjhidThHZklQc0gwSTNmeVZneGU4ejUzK1M2UW1RYkd4eWZKVnFFVTdiUHo5
        S1g3REEvdFcxT3lycmZSSHM1Nk9sZWovUjZnaGZlT2hXUXFRbW8vV1ZlKzc3YXdp
        UjhIVStyd2FJdFN6OGJmdlIzUFhVYlgxc1UvOS9vRC9XekJwTTVtTjBOSFlldmlM
        aGhCREpsUktFczhtbWNqQWFRcnEzQ1BjZVdsVEIvMGp6UHJhSTFGZEEwSFNxNGU2
        TVBSaXBobC8vOFhrdEltTkpyMjU1TXNLVVY4OHg0NFVMd080RFlMME96SU5vdDFZ
        RG9ib2Qyak1MVGIyNnhlQ002dy94Vm1qRG9sZUNkOWZydTdIWk03YlJnZ1lRdGcx
        dm54YnBpOXZYbnFqdnBGclR6SmQySVc4WVUxRzd4dERpNmdUVmhXSE4yazdHeE0z
        UmplcTN6Ny9BajJEZVlsNTdBc25kTVRVTCtwaWZiY0YzR1lMUGpaZlZ5bXpzWWZk
        Z3pxMUdnTC9UbFZJNGp2REd3Q3pVOExpbnNleTBHaFIvYVQzUjFhbFJZZHBGTzRO
        MTliL3NJV1ppR2lDMTBIQ1ZTcmNML3FIb2lxdE5RVVlneDE0QVhxMHlVUzRuVWMy
        RUVaa3dZNGlTcitFcWtuSko5NlJKN1NJSmxyNStQb1hhSVg2NjZWdVFYQ1ZxRXAx
        ajVIMlQvdDduS1huc0FveHZtZmNiNWtpZ3dYV1pmcWR0bk16V1NoTEJPS3BDUQov
        TGVxQlRHNXFpcnVGL25QMHViemVBTysxekJMakN4OVEwTlN4RUhPL25NCi0tLSBF
        Q0RxVHVaazR3MU1hZ0RFSXBKbXhrTktPSlNDeEdWdkJoYU1BNE1pWXV3Ctz4n+ai
        hH82pySZd4CXxKgpY+XaeCyjrXE+Z0UlJ/AX2oHa0/lPrVLEQTcNVnSlQUz0/HlA
        bA+ICk3ukQhsFxg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1w2c866fvyx79vj9t335rcrpgqtsqatax3gcdk73jj55zpf9d6qsvp9mgd0jhv4rseqtcp9rvxpw8wgjtccqeddqgj2rdjq932hkrrzavcahztwaerstr6zam09zhfdf68809zvvak2lw3xsqz9ktvqln0z383n28gwahr7jgeq7th2np5qhk9fe755rkyjsxshs3eqqj5z0kzwrzc8xw2ecclwwqk0m9cagjq8wz0f392syy0rsp7h0md6wwtzg8q56u2eckujf8kp6uwjwffqhxkw5c2zyuz7t8k6etfpuynpvh260zuz5nyltn9cexyw3fy5jeg774tdgahz3su7kehpwmnwwt8x2xhvg2xcf6gpxj2k39e262qpn3uxc46sf59mlfh2pzffzrfg8ujsjcrgf8vp6nhfxyhwx6v6eznmrv98ssn03jv6mp0t5f92sgufjkqly6suxj0l49c9c3my4p83gcdydvk3d3wu7g98gmcskjvegagx2pumx63rx8xqvh8qzt57xqeq7ttplkhzkf5jnna2aexftw47zulmlh8p2z2j0lmvfnpdd8lu2eklt69lsufy4qm93j6lqxfwzys0hg0kdr24xgg7672zvpevr9w2wyzmvzzycuueglssrvhham3fu236hgt27vjgez80y0s8rn7yqe87e9hx8w0vydza3qcd9nsuc9rypnj6w4zg07err67texezuhxeqy3pf3rzhrm3v5kq29a5an3xjy8v22fpy6uqcmucmnautujp06etfz4wt2eutfxj24gj5nrgewvsshmnzjuc6t8ckzr5kzcfugw5978fjkrceeuvt2xhmyf8fjeg20j3sl2sz50e9zlwg4pe3d2l84q4x6srp8svp4jpejjkz4t2uwwka5jdchasn8s5fnk43a5fw0kad8y4mc9fdtgdn25wkp537ugkn5fzf00gys8gqnkdyv2hec5wc4d8pvappqgwde370ud02xzlpwtknzme7rr4w45yznh2cue9edmkt52cypgtkz2x0xju829ym2tdjdq64tljczcs5nx8y5gqlg09acpwm2dwcujfq2kudgexf2dzpada53juvfvsfu5c8a9xagsar988kr84wxd5en2chpucztu7spzp5mdy284u8tev8gkpxnmsq0dvenvkqcfm3hf9m4wkwuf2qkdhufu69ch88d82zzeqqsx96skwfujsqz08nwq9q8qwv7tezpmra3m73qkf9vkeygg9xuzvakkkvzwjphsqd6kaxr74yyxaj9nnx8w044zw5r2572wspjdpcv3q2s7awn8fa8gh6lu6kwn69rhesvw9f9hyfz8d764sdsfdpnmqtq7av98zmjscejj6g4ahz5f365d6xjreqq8xuuyu4njycg892mut460zjf0smnjfg8fmre3a6vvr2qdkeqf2zg8tys84fkdle36grqhxy6gl3r63fz4j2u4v42nr0zxctjjta2nv28kgcwea5jem9rgnvr02re8fq26kvv6cvhdkfc2d63cl4nhn8lpczqdk4j4auvnladdtsl9pecgau3vlefw64fhfjypnycswzyjjmyqx9tzz4x9aydvv6hgd8ld645t7sx0px2qzhevqvq5684kh9apnq9zmypwaakqewurv30cf3tlcu6pg6m9a4uc7m3dzaf4f6yrn29fgnxfr0sj8f3ve58jxvcrvwgzlq8g4njw2y6kxt6tvvu5zu52yknzjkgefcuqcqq3s3p2rrc567fhesyzzz0dzr62g2mazyrqfqpv0d5kp8ykaagx7t8vky3njj5cefqtqcs5f6wdysueqs4pq0gt5fy2qujlw43nz62cyxwkhvs9e0gdf8zwxa0tlxq38qxw0u9sch8dsjacx0fvqwsa8tcqhlpc4vye4het9r0s7ertgsj2pu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T19:42:02Z"
  mac: ENC[AES256_GCM,data:ZabLRGDwZoH26RP0fHnFK/QcVu+ANrREo2yv+AblQw3v1B6YfVzu62rT3VCk8iOSdVucCpHQEEPO/8m/N06VU/4+8pQAQf+gkM5Ag6bbg2PVLWw/D8WebCApqMJq7o/uzXqKgdeRwRXHi6hwxD/agBfB158U8nOKGIryhOMT128=,iv:OM3JkgYL1q8XdjjELQwcgsz9iGg+dzbvX2kQ9FhAt+M=,tag:kgEvAHKiqoumqZ7c4CE6AA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
