---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: isp2-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter-isp2.o11y.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - fastnas.internal
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-isp2
      action: replace
# ---
# # yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: lan-nfs
# spec:
#   jobName: nfs_probe
#   module: tcp_connect
#   prober:
#     url: blackbox-exporter-lan.o11y.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#         - expanse.internal:2049
#   metricRelabelings:
#     - targetLabel: service
#       replacement: blackbox-exporter-lan
#       action: replace
# ---
# # yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: lan-slzb-ultima
# spec:
#   jobName: slzb_ultima_probe
#   module: icmp
#   prober:
#     url: blackbox-exporter-lan.o11y.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#         - slzb-ultima.internal
#   metricRelabelings:
#     - targetLabel: service
#       replacement: blackbox-exporter-lan
#       action: replace
